### ISSUE TITLE
Getting response but payment unsuccessful

### ISSUE THREAD

**Issue by debeniter86** [lemonstand/omnipay-elavon#1]
Hi, 

I am getting the response but not able to see the transaction on elavon credit card list. Can you please help me what's wrong am doing.

```
        $gateway = Omnipay::create('Elavon_Converge');
        $gateway->setMerchantId('******');
        $gateway->setUsername('webpage');
        $gateway->setPassword('******');

        // Test mode hits the demo endpoint.
        $gateway->setTestMode(true);

       $card = array('number' => '4111111111111111', 'expiryMonth' => '10', 'expiryYear' => '20', 'cvv' => '123');

            $params = array(
                'amount'                => 10.00,
                'card'                  => $card,
                'ssl_invoice_number'    => 1,
                'ssl_show_form'         => 'false',
                'ssl_result_format'     => 'ASCII'
            );

            $response = $gateway->purchase($params)->send();

            if ($response->isSuccessful()) {
                echo('success');
                echo('<pre>');print_r($response); exit;
            } else {
                echo('Error');
                echo('<pre>');print_r($response);
                exit;
                //throw new Exception($response->getMessage());
            }
```
## Response -

[data:protected] => Array
        (
            [ssl_status] => TEST MODE
            [ssl_card_number] => 41**********1111
            [ssl_exp_date] => 1020
            [ssl_amount] => 10.00
            [ssl_salestax] => 
            [ssl_invoice_number] => 1
            [ssl_departure_date] => 
            [ssl_completion_date] => 
            [ssl_issue_points] => 
            [ssl_promo_code] => 
            [ssl_enrollment] => 
            [ssl_result] => 0
            [ssl_result_message] => APPROVED
            [ssl_txn_id] => 00000000-0000-0000-0000-00000000000
            [ssl_approval_code] => 123456
            [ssl_cvv2_response] => P
            [ssl_avs_response] => X
            [ssl_account_balance] => 0.00
            [ssl_txn_time] => 03/10/2016 06:22:58 AM
            [ssl_loyalty_account_balance] => 
            [ssl_loyalty_program] => 
            [ssl_access_code] => 
            [ssl_tender_amount] => 
            [ssl_account_status] => 
            [ssl_card_type] => CREDITCARD
            [ssl_card_short_description] => VISA
        )

**Comment by aperdomo** [comment]
@debeniter86,

Apologies for not seeing this sooner. If you're getting a valid response, you should be okay (and shouldn't be an issue with the driver).

Try contacting their [support channel](https://www.convergepay.com/converge-webapp/developer/#/welcome). If you email, feel free to [copy me](andy@lemonstand.com).
